
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sjpa
  name: sjpa
spec:
  ports:
  - name: 8080-9093
    port: 8080
    protocol: TCP
    targetPort: 9093
  selector:
    app: sjpa
  type: ClusterIP
status:
  loadBalancer: {}
